<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_chartofaccount_model extends CI_Model
{

    public $table = 'data_chartofaccount';
    public $id = 'id_akun';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_akun', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama_akun', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('saldo_awal', $q);
	$this->db->or_like('saldo', $q);
	$this->db->or_like('saldo_akhir', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('phu', $q);
	$this->db->or_like('laporan_neraca', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_akun', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama_akun', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('saldo_awal', $q);
	$this->db->or_like('saldo', $q);
	$this->db->or_like('saldo_akhir', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('phu', $q);
	$this->db->or_like('laporan_neraca', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_chartofaccount_model.php */
/* Location: ./application/models/Data_chartofaccount_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-08 06:26:56 */
/* http://harviacode.com */